---
- name: Debian family
  command: echo "Debian family"

- name: Add universe repository into sources list
  become: true
  apt_repository:
    repo: deb http://us.archive.ubuntu.com/ubuntu xenial main universe
    state: present

- name: Install the build dependencies for package python-dev
  become: true
  apt:
    pkg: "{{ item }}"
    state: present
  with_items: "{{ ubuntu_packages }}"

- name: Create temp directory for work
  command: mktemp -d
  changed_when: false
  register: temp_dir

  #- name: Download get-pip.py
  #become: true
  #get_url: 
  #  url: "{{ pip_url }}"
  #    dest: /tmp

- name: Copy downloaded get-pip.py
  become: true
  copy: 
    src: get-pip.py
    dest: /tmp/get-pip.py

- name: Install pip
  become: true
  shell: python get-pip.py
  args:
    chdir: /tmp

- name: Copy requirements.txt to /tmp
  become: true
  copy:
    src: files/requirements.txt
    dest: /tmp/requirements.txt

- name: Install pip packages
  become: true
  pip:
    requirements: requirements.txt
    state: present
  args:
    chdir: /tmp
